services:
  database:
    container_name: ${CONTAINER_BASENAME}_database
    image: mariadb:jammy
    networks:
      - chevereto
    volumes:
      - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"] # MariaDB
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: user_database_password

  php:
    container_name: ${CONTAINER_BASENAME}_php
    image: ${IMAGE}
    networks:
      - chevereto
    volumes:
      - storage:/var/www/html/images/
      - chevereto:/var/www/html/
      - type: bind
        source: ${SOURCE}
        target: /var/www/chevereto
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      CHEVERETO_ENVIRONMENT: dev
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: user_database_password
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: ${HOSTNAME}
      CHEVERETO_HOSTNAME_PATH: ${HOSTNAME_PATH}
      CHEVERETO_HTTPS: ${HTTPS}
      CHEVERETO_ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CHEVERETO_MAX_UPLOAD_SIZE: 8G
      CHEVERETO_SESSION_SAVE_HANDLER: redis
      CHEVERETO_SESSION_SAVE_PATH: "tcp://redis:6379?auth[]=redis_password&prefix=chv:SESSION:"
      CHEVERETO_ERROR_LOG_CLI: /proc/1/fd/2
      CHEVERETO_ERROR_LOG_CRON: /proc/1/fd/2
      CHEVERETO_ERROR_LOG: /dev/stderr
      CHEVERETO_SERVICING: docker
      # CHEVERETO_SERVICING: server # uncomment to enable application filesystem upgrades
      CHEVERETO_CACHE_DRIVER: redis
      CHEVERETO_CACHE_HOST: redis
      CHEVERETO_CACHE_PORT: 6379
      CHEVERETO_CACHE_USER:
      CHEVERETO_CACHE_PASSWORD: redis_password

  redis:
    container_name: ${CONTAINER_BASENAME}_redis
    image: redis:8
    networks:
      - chevereto
    volumes:
      - redis:/data
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --appendonly yes --requirepass redis_password

volumes:
  database:
  storage:
  chevereto:
  redis:

networks:
  chevereto:
