#!/usr/bin/env bash
set -e
if [ -f "${ENV_FILE}" ]; then
    echo "[!] File ${ENV_FILE} already exists"
    exit 1
fi
read -p "CHEVERETO_LICENSE_KEY: " CHEVERETO_LICENSE_KEY
read -p "DOMAIN: " DOMAIN
read -p "EMAIL_HTTPS: " EMAIL_HTTPS
read -p "CLOUDFLARE_TOKEN: " CLOUDFLARE_TOKEN
read -p "CLOUDFLARE_ZONE_ID: " CLOUDFLARE_ZONE_ID
read -p "CLOUDFLARE_ACCOUNT_ID: " CLOUDFLARE_ACCOUNT_ID
read -p "CLOUDFLARE_A_NAME: " CLOUDFLARE_A_NAME
cat >${ENV_FILE} <<EOM
CHEVERETO_LICENSE_KEY=${CHEVERETO_LICENSE_KEY}
DOMAIN=${DOMAIN}
EMAIL_HTTPS=${EMAIL_HTTPS}
CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
CLOUDFLARE_A_NAME=${CLOUDFLARE_A_NAME}
EOM
echo "[OK] Configuration stored at .env"
